CREATE TABLE IF NOT EXISTS axminions_types (id INTEGER AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64));

CREATE TABLE IF NOT EXISTS axminions_minions (id INTEGER AUTO_INCREMENT PRIMARY KEY, location_id INTEGER, owner_id INTEGER, type_id SMALLINT, `level` SMALLINT, charge BIGINT, facing TINYINT, tool BLOB, extra_data BLOB);

CREATE TABLE IF NOT EXISTS axminions_locations (id INTEGER AUTO_INCREMENT PRIMARY KEY, world_id INTEGER, x INTEGER, y INTEGER, z INTEGER);

CREATE TABLE IF NOT EXISTS axminions_worlds (id INTEGER AUTO_INCREMENT PRIMARY KEY, world_uuid VARCHAR(36));

CREATE TABLE IF NOT EXISTS axminions_users (id INTEGER AUTO_INCREMENT PRIMARY KEY, uuid VARCHAR(36), name VARCHAR(16), extra_slots INTEGER, island_slots INTEGER);