name: "AxMinions"
main: "com.artillexstudios.axminions.AxMinionsPlugin"
version: "1.0"
api-version: 1.19
softdepend:
  - RoseStacker
  - WildStacker
  - CMI
  - Vault
  - EconomyShopGUI
  - Essentials
  - ShopGUIPlus
  - BentoBox
  - GriefPrevention
  - IridiumSkyBlock
  - KingdomsX
  - Lands
  - SuperiorSkyBlock2
  - WorldGuard
  - PlotSquared